"""Add Photo

Revision ID: 33bc0b506c2
Revises: 37c15fe4288
Create Date: 2014-05-09 19:14:42.174569

"""

# revision identifiers, used by Alembic.
revision = '33bc0b506c2'
down_revision = '37c15fe4288'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('saved_filename', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    ### end Alembic commands ###
